// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdl-BvZFSmGjzMeORrXJOrss-NISeQNU0',
    appId: '1:482616969632:web:d97665737a7a0391ab3cc5',
    messagingSenderId: '482616969632',
    projectId: 'crudlabdb',
    authDomain: 'crudlabdb.firebaseapp.com',
    storageBucket: 'crudlabdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGNnvJij00nalw3cGQ9DMNDRB5MPIO6n8',
    appId: '1:482616969632:android:ba8a43bb078d2a98ab3cc5',
    messagingSenderId: '482616969632',
    projectId: 'crudlabdb',
    storageBucket: 'crudlabdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5FiIgcUH60iByS9nFNQRiQerRNVvctA',
    appId: '1:482616969632:ios:e172aa6c327e2550ab3cc5',
    messagingSenderId: '482616969632',
    projectId: 'crudlabdb',
    storageBucket: 'crudlabdb.appspot.com',
    iosClientId: '482616969632-qc89huua8kbdub3bp8mg4mo3a2am2rk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5FiIgcUH60iByS9nFNQRiQerRNVvctA',
    appId: '1:482616969632:ios:e172aa6c327e2550ab3cc5',
    messagingSenderId: '482616969632',
    projectId: 'crudlabdb',
    storageBucket: 'crudlabdb.appspot.com',
    iosClientId: '482616969632-qc89huua8kbdub3bp8mg4mo3a2am2rk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );
}
